### ISSUE TITLE
Cannot have permission to edit map

### ISSUE THREAD

**Issue by fatinghenji** [karellodewijk/wottactics#18] opened 2018-04-21 16:23 UTC
I have logged in to my Google account using Google Chrome. When I choose to create a new map, it shows that I have no right to edit。By the way, I use the Rainbow 6 - the siege of the tactical board

**Comment by NikoGrano** [comment] 2019-01-17 20:01
Could not reproduce. Should be marked as closed.

**Closed as completed** 2021-09-26 07:07 UTC
